name: Update Readme

on: [push]

jobs:
  update-readme:
    
    runs-on: ubuntu-latest

    container:
      image: docker://golang:latest

    steps:
    - uses: actions/checkout@v1

    - name: attach branch
      run: git switch -

    - name: Install gomplate
      run: go get github.com/hairyhenderson/gomplate/cmd/gomplate

    - name: make README
      run: make readme
    - name: contributor
      run : git config --global user.name "guiadco" && git config --global user.email "guiadco@geekhomeinside.com"

    - name: update readme on master
      run: git add -A . && git commit -m "test" && git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}