name: Update Readme

on: [push]

jobs:
  update-readme:
    
    runs-on: ubuntu-latest

    container:
      image: docker://golang:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install gomplate
      run: go get github.com/hairyhenderson/gomplate/cmd/gomplate

    - name: make README
      run: make readme

    - name: update readme on master
      run: git push 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}