name: Update Readme

on: [push]

jobs:
  update-readme:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install golang
      run: sudo apt-get install golang-go

    - name: Install gomplate
      run: go get github.com/hairyhenderson/gomplate/cmd/gomplate

    - name: make README
      run: make readme

    - name: Commit files
      run: |
        git config --local user.email "guiadco@geekhomeinside.com"
        git config --local user.name "GitHub Action - GuiAdCo"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}