name: Update Readme

on: [push]

jobs:
  update-readme:
    
    runs-on: ubuntu-latest

    container:
      image: docker://node:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install gomplate -D

    - name: make README
      run: make readme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}