name: Update Readme

on: [push]

jobs:
  update-readme:
    
    runs-on: ubuntu-latest

    container:
      image: docker://golang:latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: master

    - name: Install gomplate
      run: go get github.com/hairyhenderson/gomplate/cmd/gomplate

    - name: status on master
      run: git status
    
    - name: switch temp branch
      run: git checkout -b temp

    - name: make README
      run: make readme

    - name: Commit files
      run: |
        git config --local user.email "guiadco@geekhomeinside.com" 
        git config --local user.name "GitHub Action - GuiAdCo" 
        git add -A .
        git commit -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}